### PR TITLE
Add support for label descriptions

### PR DESCRIPTION
**Pull request by mklemme**
[Api docs](https://developer.github.com/v3/issues/labels/#parameters) says that descriptions for labels are supported but I can't get the api working. Pinged them on [twitter](https://twitter.com/mklemme/status/1029946631678914561). Waiting to hear back.

This pr adds support for label descriptions. #17 might be too stale to merge so I was going to try again.

### CODE REVIEW

**Comment by thomas-mcdonald** [comment]
@mklemme Are you sending the preview header? https://developer.github.com/changes/2018-02-22-label-description-search-preview/

**Comment by Tjoosten** [comment]
Any update on this one?

**Comment by mklemme** [comment]
I can try it again tonight. The response I got back was basically "it should be working"

**Comment by mklemme** [comment]
I was able to create labels with descriptions but I'm having an encoding issue. 

So the default description for `bug` would return this:
```
var labels = [
  { "name": "bug", "color": "#fc2929", "description": "Something isn't working" },
  { "name": "duplicate", "color": "#cccccc", "description": "This issue or pull request already exists" }
];

gitLabel.add(config, labels)

{ id: 12345678,
  node_id: 'HEX123',
  url: 'https://api.github.com/repos/invisiblehats/class_name/labels/bug',
  name: 'bug',
  color: 'fc2929',
  default: true,
  description: 'Something isn%27t working' }
```

Anyone know what's happening? `JSON.stringify` only escapes to `"Something isn\'t working"`. The [docs](https://developer.github.com/v3/issues/labels/#example) for creating a label uses the same thing but works.

**Comment by mklemme** [comment]
Otherwise this is working fine! :tada:

Here's where I tested them: [invisiblehats/class_name/labels](https://github.com/invisiblehats/class_name/labels)

**Pull request closed without merging**
